(* Generated by Mirage (Sun, 27 Jul 2014 10:42:02 GMT). *)

open Lwt

let _ = Printexc.record_backtrace true

let console1 () =
  Console.connect "0"

module M3 = Dispatch.Main(Console)

let t3 = console1

let static1 () =
  Static1.connect ()

module M2 = Dispatch.Main(Console)(Static1)

let t2 () =
  console1 () >>= function
  | `Error e -> fail (Failure "console1")
  | `Ok console1 ->
  static1 () >>= function
  | `Error e -> fail (Failure "static1")
  | `Ok static1 ->
  return (`Ok (console1, static1))

let net_tap0 () =
  Netif.connect "tap0"

module Stackv41 = struct
  module E = Ethif.Make(Netif)
  module I = Ipv4.Make(E)
  module U = Udpv4.Make(I)
  module T = Tcpv4.Flow.Make(I)(OS.Time)(Clock)(Random)
  module S = Tcpip_stack_direct.Make(Console)(OS.Time)(Random)(Netif)(E)(I)(U)(T)
  include S
end

let stackv41 () =
  console1 () >>= function
  | `Error _    -> fail (Failure "console1")
  | `Ok console ->
  net_tap0 () >>= function
  | `Error _      -> fail (Failure "net_tap0")
  | `Ok interface ->
  let config = {
    V1_LWT.name = "stackv41";
    console; interface;
    mode = `IPv4 (Ipaddr.V4.of_string_exn "10.0.0.2", Ipaddr.V4.of_string_exn "255.255.255.0", [Ipaddr.V4.of_string_exn "10.0.0.1"]);
  } in
  Stackv41.connect config

module Http1_channel = Channel.Make(Stackv41.TCPV4)
module Http1 = HTTP.Make(Http1_channel)

let http1 () =
  stackv41 () >>= function
  | `Error _  -> fail (Failure "stackv41")
  | `Ok stack ->
  let listen spec =
    Stackv41.listen_tcpv4 ~port:80 stack (fun flow ->
      let chan = Http1_channel.create flow in
      Http1.Server_core.callback spec chan chan
    );
    Stackv41.listen stack in
  return (`Ok listen)

module M1 = Dispatch.Main(Console)(Static1)(Http1.Server)

let t1 () =
  console1 () >>= function
  | `Error e -> fail (Failure "console1")
  | `Ok console1 ->
  http1 () >>= function
  | `Error e -> fail (Failure "http1")
  | `Ok http1 ->
  static1 () >>= function
  | `Error e -> fail (Failure "static1")
  | `Ok static1 ->
  M1.start console1 static1 http1

let () =
  OS.Main.run (join [t1 ()])
